# Use the official nginx image as the base image
FROM nginx:alpine

# Copy the static files from the current directory to /usr/share/nginx/html
COPY . /usr/share/nginx/html

# Expose port 80 to the host
EXPOSE 4000
