version: "3"

services:
  # PostgreSQL database
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: $PASSWORD
      POSTGRES_DB: checkers
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
